---
# tasks file for role_aws

- debug:
    msg: "{{ ansible_env.HOME }}/.aws/credentials"

- debug:
    msg: "{{ central_storage }}/aws/credentials"

- debug:
    var: aws_creds_link_status

- name: "Create .aws Directory if it doesn't Exist"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.aws"
    state: directory