---
# tasks file for role_internal

- name: "Install PIP Internal Modules"
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    extra_args: "--index-url https://{{ item.index_url | default(omit) }} --extra-index-url https://{{ item.extra_index_url | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ internal.pip_modules }}"
  when: internal.pip_modules is defined

- name: "Include Symlink Tasks for {{ item.file_name }}"
  ansible.builtin.include_tasks: symlinks.yml
  loop: "{{ internal.symlinks }}"
  when: internal.symlinks is defined

- name: ".zshrc Internal Blocks for {{ item.name }}"
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item.name }} .zshrc"
    marker_begin: 'BEGIN' 
    marker_end: 'END'
    block: |
      {{ item.block }}
  loop: "{{ internal.zshrc }}"
  when: internal.zshrc is defined

- name: .zshrc Internal Blocks PADDING
  ansible.builtin.replace:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    regexp: "(?<!\n\n)(# BEGIN ANSIBLE MANAGED BLOCK - {{ item.name }} .zshrc)"
    replace: '\n\1' 
  loop: "{{ internal.zshrc }}"
  when: internal.zshrc is defined

