---
# tasks file for role_internal

- name: "Check if requested Internal Symlinks Destination exists for {{ item.file_name }}"
  ansible.builtin.stat:
    path: "{{ item.dest_dir }}/{{ item.file_name }}"
  register: internal_dest_file

- name: "Create Internal Symlinks for {{ item.file_name }}"
  ansible.builtin.file:
    src: "{{ central_storage }}/{{ item.src_dir }}/{{ item.file_name }}"
    dest: "{{ item.dest_dir }}/{{ item.file_name }}"
    state: link
  when: not internal_dest_file.stat.exists