---
# tasks file for macos_bootstrap

- name: Determine Homebrew ownership variables
  set_fact:
    homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
    homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'

- name: "Install podman HomeBrew Packages"
  homebrew:
    name: "{{ brew_packages }}"
    state: present

- name: "Check if docker symbolic link exists"
  ansible.builtin.stat:
   path: "{{ docker_path }}"
  register: docker_link_status

- name: "Create a symbolic link for docker to podman"
  ansible.builtin.file:
    src: "{{ podman_path }}"
    dest: "{{ docker_path }}"
    owner: root
    state: link
  when: docker_link_status.islnk is defined and docker_link_status.islnk
  become: true

- name: "Include PodMan Machine Tasks"
  ansible.builtin.include_tasks: podman_machine.yml