---
# tasks file for macos_bootstrap

- name: "Install podman HomeBrew Packages"
  homebrew:
    name: "{{ brew_packages }}"
    state: present

- name: "Create a symbolic link for docker to podman"
  ansible.builtin.file:
    src: /usr/local/bin/podman
    dest: /usr/local/bin/docker
    owner: mschimmel
    group: admin
    force: true
    state: link