---
# tasks file for role_shell_zsh

- name: Include oh-my-zsh Tasks
  ansible.builtin.include_tasks: oh_my_zsh.yml

- name: Include .custom_alias Tasks
  ansible.builtin.include_tasks: custom_alias.yml

- name: Copy and Paste .zshrc Configuration
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0640