---
# tasks file for role_shell_zsh

- name: Include oh-my-zsh Tasks
  ansible.builtin.include_tasks: oh_my_zsh.yml

- name: Copy and Paste .custom_alias Configuration
  ansible.builtin.copy:
    src: custom_alias
    dest: "{{ ansible_env.HOME }}/.custom_alias"

- name: Copy and Paste .zshrc Configuration
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"