---
# tasks file for role_finder

- name: Get macOS Defaults
  ansible.builtin.shell:
    cmd: defaults read com.apple.Finder | grep AppleShowAll
  changed_when: false
  failed_when: false
  register: macos_defaults

- name: Reveal Hidden Files and Folders
  ansible.builtin.shell:
    cmd: >
      defaults write com.apple.Finder AppleShowAllFiles -bool "true"
  register: hidden_files_and_folders
  when: >
    not (macos_defaults | regex_search('AppleShowAllFiles = true | AppleShowAllFiles = 1'))

- name: Restart Finder
  ansible.builtin.command: killall Finder
  changed_when: hidden_files_and_folders.changed