---
# tasks file for role_shell_zsh

- name: Get macOS Defaults
  ansible.builtin.shell:
    cmd: defaults read
  changed_when: false
  register: macos_defaults

- debug:
    msg: "{{ macos_defaults | community.general.json_query('*') }}"

# - name: Reveal Hidden Files and Folders
#   ansible.builtin.shell:
#     cmd: defaults write com.apple.Finder AppleShowAllFiles true
#   when: macos_defaults | community.general.json_query('domain.server[*].name')
#   register: hidden_files_and_folders

# - name: Restart Finder
#   ansible.builtin.shell:
#     cmd: defaults write com.apple.Finder AppleShowAllFiles true
#   changed_when: hidden_files_and_folders.changed