---
# tasks file for role_python

- name: Determine Homebrew ownership variables
  set_fact:
    homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
    homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'

- name: "Install Python HomeBrew Packages"
  homebrew:
    name: "{{ brew_packages }}"
    state: present