---
# tasks file for role_python

- name: "Install Python HomeBrew Packages"
  homebrew:
    name: "{{ brew_packages }}"
    state: present

- name: Include zshrc Tasks
  ansible.builtin.include_tasks: zshrc.yml

- name: Include pyENV Global Tasks
  ansible.builtin.include_tasks: pyenv_global.yml

- name: "Install PIP Modules"
  ansible.builtin.pip:
    name: "{{ pip_installed_modules }}"
  become: true
  become_user: "{{ ansible_env.USER }}"