---
# tasks file for role_python

- name: Check installed Version of Python
  ansible.builtin.command: pyenv versions
  changed_when: false
  become: true
  become_user: "{{ ansible_env.USER }}"
  register: pyenv_version

- name: Install pyenv Global Python Version
  ansible.builtin.command: pyenv install {{ global_python_version }}
  register: pyenv_install
  changed_when: pyenv_install is search('Installed Python-'+ global_python_version + ' to '+ ansible_env.HOME + '/.pyenv/versions/' + global_python_version)
  become: true
  become_user: "{{ ansible_env.USER }}"
  when: >
    not (global_python_version in pyenv_version.stdout)

- name: Show pyenv Install output if completed
  debug:
    msg: "{{ pyenv_install.stdout_lines + pyenv_install.stderr_lines }}"
  when: pyenv_install.changed