---
# tasks file for role_python

- name: python .zshrc Block
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - python .zshrc"
    marker_begin: 'BEGIN' 
    marker_end: 'END'
    block: |
      # PYENV
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
  
- name: python .zshrc Block PADDING
  ansible.builtin.replace:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    regexp: "(?<!\n\n)(# BEGIN ANSIBLE MANAGED BLOCK - python .zshrc)"
    replace: '\n\1' 