---
# tasks file for role_ansible

- name: "Install PIP Modules"
  ansible.builtin.pip:
    name: "{{ pip_installed_modules }}"
  become: true
  become_user: "{{ ansible_env.USER }}"

- name: "Include pyENV virtualENV Tasks"
  ansible.builtin.include_tasks: virtualenv.yml